# Select the tasks
task : 'denoising'
# task : 'component_denoising'
# task : 'inst_frequency'

N: 1024
SNRin: [-20,-10,0,10,20] #[-20,-15,-10,-5,0,5,10,15,20]
repetitions: 30
parallelize: False
verbosity: 0
signal_ids: [
                'McDampedCos',
                'McCrossingChirps',             # Crossing-components  
                'McSyntheticMixture5',
              ]



# Run again the same benchmark but only for new methods:
add_new_methods: False
